export const queryKeys = {
  banner: "banner",
  newReleases: "newReleases",
  popular: "popular",
  topsongs: "topsongs",
  chills: "chills",
  top100: "top100",
  albumHot: "albumHot",
  infoSong: "infoSong",
  detailPlaylist: "detailPlaylist",
  detailArtist: "detailArtist",
  chart: "chart",
  lyric: "lyric",
  suggest: "suggest",
  search: "search",
  me: "me",
};
